stages:
  - build

docker-build:
  image: docker:27.1.2-dind
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_DOCKER_HUB_USER" -p "$CI_DOCKER_HUB_PASSWORD" docker.io
  script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - export VERSION=$(cat VERSION)
    - docker buildx create --use --name buildkit_docker_mldonkey
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64
          -t carlonluca/mldonkey:$VERSION
          -t carlonluca/mldonkey:dev
          -t carlonluca/mldonkey:latest
          .
    - docker buildx stop buildkit_docker_mldonkey
    - docker buildx rm buildkit_docker_mldonkey
