stages:
  - build

docker-build:
  image: carlonluca/docker-multiarch:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_DOCKER_HUB_USER" -p "$CI_DOCKER_HUB_PASSWORD" docker.io
  script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - export VERSION=$(cat VERSION)
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64
          -t carlonluca/mldonkey:dev-6fbc501-d63fb58
          -t carlonluca/mldonkey:latest
          -t carlonluca/mldonkey:dev
          .