FROM ubuntu:oracular

RUN \
    export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -y --no-install-recommends git build-essential \
        autoconf wget libz-dev libbz2-dev libmagic-dev libnatpmp-dev \
        libupnp-dev libgd-dev ca-certificates ocaml camlp4 ocaml-compiler-libs ocaml-nox \
        libminiupnpc-dev librsvg2-dev libnum-ocaml-dev libc6-dev libcurl-ocaml-dev